version: "3.8"

networks:
  nextjs:

services:
  site:
    build:
      context: .
      dockerfile: nextjs.dockerfile
      target: dev
    container_name: nextjs
    volumes:
      - ./nextjs:/usr/src/app
      - nextjs-dev-node_modules:/usr/src/app/node_modules
      - nextjs-dev-next:/usr/src/app/.next
    restart: always
    ports:
      - "3000:3000"
    networks:
      - nextjs

  nextjs_npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./nextjs:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["npm"]

  studio_npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./studio:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["npm"]

  nextjs_npx:
    image: node:alpine
    container_name: npx
    volumes:
      - ./nextjs:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["npx"]

  studio_npx:
    image: node:alpine
    container_name: npx
    volumes:
      - ./studio:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["npx"]

volumes:
  nextjs-dev-node_modules:
  nextjs-dev-next:
