version: "3.8"

networks:
  portfolio-website:

services:
  nextjs:
    build:
      context: .
      dockerfile: nextjs.dockerfile
      target: dev
    container_name: nextjs_pw
    volumes:
      - ./nextjs:/usr/src/app
      - nextjs-dev-node_modules:/usr/src/app/node_modules
      - nextjs-dev-next:/usr/src/app/.next
    ports:
      - "3000:3000"
    restart: always
    networks:
      - portfolio-website

  npm:
    image: node:alpine
    container_name: npm_pw
    volumes:
      - ./nextjs:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - nextjs
    networks:
      - portfolio-website
    entrypoint: ['npm']

volumes:
  nextjs-dev-node_modules:
  nextjs-dev-next:
